version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: meu_redis_cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      # Armazena dados em um volume nomeado para que não se percam
      - redis_data:/data

# Onde os dados serão salvos
volumes:
  redis_data: